version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - dbData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - postgres-ntw

networks:
  postgres-ntw:
    driver: bridge

volumes:
  dbData:
